name: eadukalthedi
description: "A new Flutter project."

# Prevents accidental publication to pub.dev.
publish_to: 'none'

# Application version details.
version: 1.0.0+1

# Flutter SDK version.
environment:
  sdk: '>=3.0.0 <4.0.0'

# Application dependencies.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  gap: ^3.0.1
  page_transition: ^2.1.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  flutter_gen: ^5.8.0
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.6
  share_plus: ^10.1.2
  build_runner: ^2.4.14
  animated_botton_navigation: ^0.0.7
  lucide_icons_flutter: ^1.2.5
  dio: ^5.7.0

# Development dependencies for testing and linting.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adding assets.
  assets:
    - assets/pngs/
    - assets/svgs/

  # Adding custom fonts.
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/helvetica/HelveticaNeueBlackItalic.otf
        - asset: assets/fonts/helvetica/HelveticaNeueBlack.otf
        - asset: assets/fonts/helvetica/HelveticaNeueBoldItalic.otf
        - asset: assets/fonts/helvetica/HelveticaNeueBold.otf
        - asset: assets/fonts/helvetica/HelveticaNeueHeavyItalic.otf
        - asset: assets/fonts/helvetica/HelveticaNeueHeavy.otf
        - asset: assets/fonts/helvetica/HelveticaNeueItalic.ttf
        - asset: assets/fonts/helvetica/HelveticaNeueLightItalic.otf
        - asset: assets/fonts/helvetica/HelveticaNeueLight.otf
        - asset: assets/fonts/helvetica/HelveticaNeueMediumItalic.otf
        - asset: assets/fonts/helvetica/HelveticaNeueMedium.otf
        - asset: assets/fonts/helvetica/HelveticaNeueRoman.otf
        - asset: assets/fonts/helvetica/HelveticaNeueThinItalic.otf
        - asset: assets/fonts/helvetica/HelveticaNeueThin.otf
        - asset: assets/fonts/helvetica/HelveticaNeueUltraLightItalic.otf
        - asset: assets/fonts/helvetica/HelveticaNeueUltraLight.otf

